language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

before_install:
 - chmod +x gradlew

install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S

env:
  global:
    TERM=dumb

notifications:
  irc:
    channels:
      - "irc.esper.net#illyohs"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view: %{compare_url}"
      - "Build details: %{build_url}"
      - "Commit message: %{commit_message}"